import type { SiteTypeId, StockId } from "./ids";

export interface SiteType {
  id: SiteTypeId;
  name: string;
  blurb: string;
  hp: number;
  strategic: boolean;
  isAa: boolean;
  isAirfield: boolean;
  radius: number;
  drawSize: number;
  sprite: string;
  produce: Partial<Record<StockId, number>>;
  aaRange: number;
  aaRate: number;
  aaDamage: number;
  aaSpeed: number;
}

export const SITE_TYPES: Record<SiteTypeId, SiteType> = {
  hq: {
    id: "hq",
    name: "Command",
    blurb: "Headquarters. Losing it hurts the whole grid.",
    hp: 420,
    strategic: true,
    isAa: false,
    isAirfield: true,
    radius: 42,
    drawSize: 78,
    sprite: "hq",
    produce: { electronics: 1.4 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  factory: {
    id: "factory",
    name: "Factory",
    blurb: "Airframes and parts.",
    hp: 300,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 40,
    drawSize: 76,
    sprite: "factory",
    produce: { parts: 4.2 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  refinery: {
    id: "refinery",
    name: "Refinery",
    blurb: "Fuel for the long hops.",
    hp: 280,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 40,
    drawSize: 74,
    sprite: "refinery",
    produce: { fuel: 3.6 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  power: {
    id: "power",
    name: "Power",
    blurb: "Keeps radars and lines alive.",
    hp: 260,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 40,
    drawSize: 74,
    sprite: "power",
    produce: { electronics: 2.2, parts: 0.6 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  airfield: {
    id: "airfield",
    name: "Airfield",
    blurb: "Launch pad. If it dies, sorties crawl out of HQ.",
    hp: 240,
    strategic: true,
    isAa: false,
    isAirfield: true,
    radius: 44,
    drawSize: 80,
    sprite: "airfield",
    produce: { parts: 0.8 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  ammo: {
    id: "ammo",
    name: "Magazine",
    blurb: "Warheads and charges.",
    hp: 220,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 36,
    drawSize: 68,
    sprite: "ammo",
    produce: { warheads: 2.4 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  fuel: {
    id: "fuel",
    name: "Fuel farm",
    blurb: "Tank farm. Soft, valuable.",
    hp: 200,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 36,
    drawSize: 66,
    sprite: "fuel",
    produce: { fuel: 2.1 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  rail: {
    id: "rail",
    name: "Rail yard",
    blurb: "Logistics spine. Feeds everything slowly.",
    hp: 250,
    strategic: true,
    isAa: false,
    isAirfield: false,
    radius: 40,
    drawSize: 74,
    sprite: "rail",
    produce: { parts: 1.4, warheads: 0.6, fuel: 0.5 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
  },
  aa: {
    id: "aa",
    name: "Battery",
    blurb: "SAM / guns. Not a victory target, but it will ruin a raid.",
    hp: 170,
    strategic: false,
    isAa: true,
    isAirfield: false,
    radius: 32,
    drawSize: 58,
    sprite: "aa",
    produce: {},
    aaRange: 210,
    aaRate: 1.15,
    aaDamage: 13,
    aaSpeed: 430,
  },
};
