import type { SiteTypeId, StockId } from "./ids";
import type { StockCost } from "./drones";

export interface SiteType {
  id: SiteTypeId;
  name: string;
  blurb: string;
  hp: number;
  strategic: boolean;
  isAa: boolean;
  isEw: boolean;
  isAirfield: boolean;
  placeable: boolean;
  radius: number;
  drawSize: number;
  sprite: string;
  produce: Partial<Record<StockId, number>>;
  build: StockCost;
  aaRange: number;
  aaRate: number;
  aaDamage: number;
  aaSpeed: number;
  ewRange: number;
  ewSlow: number;
  ewJam: number;
}

function zero(): StockCost {
  return { parts: 0, fuel: 0, warheads: 0, electronics: 0 };
}

export const SITE_TYPES: Record<SiteTypeId, SiteType> = {
  hq: {
    id: "hq",
    name: "Command",
    blurb: "Command. If it dies, the match is over. Guard it with ПВО.",
    hp: 220,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: true,
    placeable: false,
    radius: 42,
    drawSize: 78,
    sprite: "hq",
    produce: { electronics: 1.4, parts: 1.8, fuel: 1.2, warheads: 0.55 },
    build: zero(),
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  factory: {
    id: "factory",
    name: "Factory",
    blurb: "Airframes and parts.",
    hp: 210,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 40,
    drawSize: 76,
    sprite: "factory",
    produce: { parts: 5.0 },
    build: { parts: 36, fuel: 4, warheads: 0, electronics: 6 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  refinery: {
    id: "refinery",
    name: "Refinery",
    blurb: "Fuel for the long hops.",
    hp: 195,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 40,
    drawSize: 74,
    sprite: "refinery",
    produce: { fuel: 4.2 },
    build: { parts: 28, fuel: 2, warheads: 0, electronics: 4 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  power: {
    id: "power",
    name: "Power",
    blurb: "Keeps radars and lines alive.",
    hp: 185,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 40,
    drawSize: 74,
    sprite: "power",
    produce: { electronics: 2.2, parts: 0.6 },
    build: { parts: 26, fuel: 4, warheads: 0, electronics: 8 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  airfield: {
    id: "airfield",
    name: "Airfield",
    blurb: "Launch pad. Range is measured from here, not from HQ.",
    hp: 200,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: true,
    placeable: true,
    radius: 44,
    drawSize: 80,
    sprite: "airfield",
    produce: { parts: 0.8 },
    build: { parts: 30, fuel: 8, warheads: 0, electronics: 4 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  ammo: {
    id: "ammo",
    name: "Magazine",
    blurb: "Warheads and charges.",
    hp: 175,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 36,
    drawSize: 68,
    sprite: "ammo",
    produce: { warheads: 2.8 },
    build: { parts: 22, fuel: 2, warheads: 4, electronics: 2 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  fuel: {
    id: "fuel",
    name: "Fuel farm",
    blurb: "Tank farm. Soft, valuable.",
    hp: 155,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 36,
    drawSize: 66,
    sprite: "fuel",
    produce: { fuel: 2.1 },
    build: { parts: 18, fuel: 2, warheads: 0, electronics: 2 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  rail: {
    id: "rail",
    name: "Rail yard",
    blurb: "Logistics spine. Feeds everything slowly.",
    hp: 190,
    strategic: true,
    isAa: false,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 40,
    drawSize: 74,
    sprite: "rail",
    produce: { parts: 1.4, warheads: 0.6, fuel: 0.5 },
    build: { parts: 28, fuel: 4, warheads: 2, electronics: 4 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  aa: {
    id: "aa",
    name: "ПВО",
    blurb: "SAM battery. Place on the approach, not only on the HQ. Two batteries hold a Geran salvo.",
    hp: 150,
    strategic: false,
    isAa: true,
    isEw: false,
    isAirfield: false,
    placeable: true,
    radius: 32,
    drawSize: 58,
    sprite: "aa",
    produce: {},
    build: { parts: 18, fuel: 4, warheads: 8, electronics: 10 },
    aaRange: 240,
    aaRate: 1.05,
    aaDamage: 13,
    aaSpeed: 440,
    ewRange: 0,
    ewSlow: 0,
    ewJam: 0,
  },
  ew: {
    id: "ew",
    name: "РЭБ",
    blurb: "Jammer. Slows and drops radio FPV. Fiber walks through it.",
    hp: 135,
    strategic: false,
    isAa: false,
    isEw: true,
    isAirfield: false,
    placeable: true,
    radius: 30,
    drawSize: 56,
    sprite: "ew",
    produce: {},
    build: { parts: 14, fuel: 4, warheads: 0, electronics: 16 },
    aaRange: 0,
    aaRate: 0,
    aaDamage: 0,
    aaSpeed: 0,
    ewRange: 190,
    ewSlow: 0.52,
    ewJam: 0.28,
  },
};

export const BUILD_ORDER: SiteTypeId[] = [
  "aa",
  "ew",
  "factory",
  "airfield",
  "refinery",
  "ammo",
  "fuel",
  "power",
  "rail",
];
